# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  verify-build-and-push-nuget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      # compile & verify project
      - name: restore dependencies
        run: dotnet restore
      - name: build the project
        run: dotnet build --configuration Release --no-restore True
      - name: test the build
        run: dotnet test --no-build True --verbosity normal

      # push nuget repo (package is created on build as the configuration in the csproj file)
      - name: add nuget package to repo
        run: |
          if [[ -z "${{ secrets.PACKAGE_MANAGEMENT }}" ]]; then echo -e "\033[91no token was set!\033[0m" && exit -1; fi
          dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name "github" --username ${{ github.repository_owner }} --password ${{ secrets.PACKAGE_MANAGEMENT }} --store-password-in-clear-text
          dotnet nuget push "QUtil/bin/Release/QUtil.MonoGame.Render*.nupkg" --source "github" --skip-duplicate --no-symbols
