# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    # set the correct directory
    - name: go to QUtil dir
      run: cd QUtil/

    # compile project
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore True --configuration Release
    - name: Test
      run: dotnet test --no-build True --verbosity normal

    # push nuget repo
    - name: push nuget
      run: dotnet nuget push "bin/Release/QUtil.MonoGame.Render.1.0.0.nupkg" --api-key ${GITHUB_TOKEN} --source "https://nuget.pkg.github.com/thepigeongenerator/index.json" --skip-duplicate --no-symbols
